import type { Order, ReturnSubmission } from './types';

// In-line SVG placeholders for clean standalone rendering
const SVG_HOODIE = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 80 80' fill='none'%3E%3Crect width='80' height='80' rx='12' fill='%23f1f3f5'/%3E%3Cpath d='M24 28L32 20H48L56 28L52 36L44 32V60H36V32L28 36L24 28Z' fill='%23343a40'/%3E%3C/svg%3E";
const SVG_SNEAKER = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 80 80' fill='none'%3E%3Crect width='80' height='80' rx='12' fill='%23eef2ff'/%3E%3Cpath d='M20 48C20 48 24 36 36 34L48 34L58 42L60 52H20V48Z' fill='%234f46e5'/%3E%3Crect x='18' y='52' width='44' height='6' rx='2' fill='%231e1b4b'/%3E%3C/svg%3E";
const SVG_CANDLE = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 80 80' fill='none'%3E%3Crect width='80' height='80' rx='12' fill='%23fef3c7'/%3E%3Crect x='28' y='32' width='24' height='32' rx='4' fill='%23d97706'/%3E%3Cpath d='M40 20C40 20 44 24 40 28C36 24 40 20 40 20Z' fill='%23f59e0b'/%3E%3C/svg%3E";
const SVG_HEADPHONES = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 80 80' fill='none'%3E%3Crect width='80' height='80' rx='12' fill='%23e6fcf5'/%3E%3Cpath d='M26 38C26 30.268 32.268 24 40 24C47.732 24 54 30.268 54 38V50C54 52.2091 52.2091 54 50 54H48V40H52V38C52 31.3726 46.6274 26 40 26C33.3726 26 28 31.3726 28 38V40H32V54H30C27.7909 54 26 52.2091 26 50V38Z' fill='%230ca678'/%3E%3C/svg%3E";
const SVG_PERFUME = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 80 80' fill='none'%3E%3Crect width='80' height='80' rx='12' fill='%23fdf2f8'/%3E%3Crect x='28' y='32' width='24' height='30' rx='6' fill='%23db2777'/%3E%3Crect x='34' y='22' width='12' height='10' rx='2' fill='%239d174d'/%3E%3C/svg%3E";
const SVG_SOCKS = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 80 80' fill='none'%3E%3Crect width='80' height='80' rx='12' fill='%23f3f4f6'/%3E%3Cpath d='M30 22H46V42L52 50C52 54 48 58 44 58H36C32 58 30 54 30 50V22Z' fill='%236b7280'/%3E%3C/svg%3E";

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord_1042',
    orderNumber: '1042',
    email: 'sarah.jenkins@example.com',
    customerName: 'Sarah Jenkins',
    orderDate: 'Aug 12, 2026',
    deliveredDate: 'Aug 15, 2026',
    currency: 'USD',
    shippingAddress: {
      street: '742 Evergreen Terrace',
      city: 'Springfield',
      state: 'OR',
      zip: '97477',
      country: 'United States',
    },
    items: [
      {
        id: 'item_1',
        name: 'Heavyweight Fleece Pullover',
        variant: 'Charcoal / Large',
        price: 88.0,
        quantity: 2,
        image: SVG_HOODIE,
        isEligible: true,
      },
      {
        id: 'item_2',
        name: 'Retro Runner Sneaker',
        variant: 'Cobalt Blue / 10.5 US',
        price: 135.0,
        quantity: 1,
        image: SVG_SNEAKER,
        isEligible: true,
      },
      {
        id: 'item_3',
        name: 'Smoked Amber Soy Candle (8oz)',
        variant: 'Warm Vanilla & Cedar',
        price: 28.0,
        quantity: 1,
        image: SVG_CANDLE,
        isEligible: true,
      },
      {
        id: 'item_4',
        name: 'Merino Wool Ankle Socks (Final Sale)',
        variant: 'Heather Grey / Medium',
        price: 14.0,
        quantity: 1,
        image: SVG_SOCKS,
        isEligible: false,
        ineligibleReason: 'Final sale item — excluded from standard returns policy',
      },
    ],
  },
  {
    id: 'ord_1088',
    orderNumber: '1088',
    email: 'alex.rivera@example.com',
    customerName: 'Alex Rivera',
    orderDate: 'Aug 14, 2026',
    deliveredDate: 'Aug 17, 2026',
    currency: 'USD',
    shippingAddress: {
      street: '1200 Grand Ave',
      city: 'Austin',
      state: 'TX',
      zip: '78701',
      country: 'United States',
    },
    items: [
      {
        id: 'item_5',
        name: 'Wireless Studio Headphones',
        variant: 'Matte Sage Green',
        price: 199.0,
        quantity: 1,
        image: SVG_HEADPHONES,
        isEligible: true,
      },
      {
        id: 'item_6',
        name: 'Rose Oud Eau De Parfum (50ml)',
        variant: '50ml Spray Bottle',
        price: 95.0,
        quantity: 1,
        image: SVG_PERFUME,
        isEligible: true,
      },
    ],
  },
  {
    id: 'ord_1005',
    orderNumber: '1005',
    email: 'expired@example.com',
    customerName: 'Morgan Lee',
    orderDate: 'May 10, 2026',
    deliveredDate: 'May 14, 2026',
    currency: 'USD',
    shippingAddress: {
      street: '55 5th Ave',
      city: 'New York',
      state: 'NY',
      zip: '10003',
      country: 'United States',
    },
    items: [
      {
        id: 'item_7',
        name: 'Heavyweight Fleece Pullover',
        variant: 'Black / M',
        price: 88.0,
        quantity: 1,
        image: SVG_HOODIE,
        isEligible: false,
        ineligibleReason: 'Delivered over 30 days ago (return window has closed)',
      },
    ],
  },
];

export const MOCK_RETURNS: Record<string, ReturnSubmission> = {
  'RET-894201': {
    returnId: 'RET-894201',
    orderNumber: '1042',
    customerEmail: 'sarah.jenkins@example.com',
    customerName: 'Sarah Jenkins',
    createdAt: 'Aug 18, 2026',
    status: 'in_transit',
    items: [
      {
        item: {
          id: 'item_2',
          name: 'Retro Runner Sneaker',
          variant: 'Cobalt Blue / 10.5 US',
          price: 135.0,
          quantity: 1,
          image: SVG_SNEAKER,
          isEligible: true,
        },
        quantity: 1,
        reason: 'doesnt_fit',
        notes: 'Runs about half a size larger than normal.',
      },
    ],
    method: {
      id: 'prepaid_label',
      name: 'Prepaid Shipping Label',
      carrier: 'USPS via Shippo',
      description: 'Prepaid label emailed when the store approved the return.',
      fee: 0,
      feeLabel: 'FREE (Protect Product)',
      estimatedDays: '3–5 business days',
      noPrinterNeeded: false,
      instructions: [
        'Print the label and attach it to your parcel.',
        'Drop it off with the carrier.',
      ],
    },
    resolution: 'original_payment',
    financials: {
      itemsTotal: 135.0,
      returnFee: 0,
      bonusCredit: 0,
      finalRefundAmount: 135.0,
    },
    tracking: {
      carrier: 'USPS',
      trackingNumber: '9400 1118 9956 2839 0192 84',
      trackingUrl: 'https://tools.usps.com/go/TrackConfirmAction?tLabels=9400111899562839019284',
      qrCodeValue: 'RET-894201',
    },
    timeline: [
      {
        status: 'return_requested',
        title: 'Return Requested',
        description: 'Return request received.',
        timestamp: 'Aug 18, 2026 · 10:14 AM',
        completed: true,
        current: false,
      },
      {
        status: 'return_approved',
        title: 'Return Authorized',
        description: 'The store approved your return and your prepaid label was emailed.',
        timestamp: 'Aug 18, 2026 · 10:15 AM',
        completed: true,
        current: false,
      },
      {
        status: 'in_transit',
        title: 'Package In Transit',
        description: 'Scanned at USPS sorting facility (Portland, OR). Estimated arrival Aug 22.',
        timestamp: 'Aug 19, 2026 · 02:45 PM',
        completed: false,
        current: true,
      },
      {
        status: 'received',
        title: 'Delivered to Returns Center',
        description: 'Package will be inspected within 24 hours of arrival.',
        timestamp: 'Estimated Aug 22, 2026',
        completed: false,
        current: false,
      },
      {
        status: 'refund_completed',
        title: 'Refund Issued',
        description: '$135.00 will be refunded to your original payment method.',
        timestamp: 'Pending inspection',
        completed: false,
        current: false,
      },
    ],
  },
  'RET-720194': {
    returnId: 'RET-720194',
    orderNumber: '1088',
    customerEmail: 'alex.rivera@example.com',
    customerName: 'Alex Rivera',
    createdAt: 'Aug 17, 2026',
    status: 'refund_completed',
    items: [
      {
        item: {
          id: 'item_6',
          name: 'Rose Oud Eau De Parfum (50ml)',
          variant: '50ml Spray Bottle',
          price: 95.0,
          quantity: 1,
          image: SVG_PERFUME,
          isEligible: true,
        },
        quantity: 1,
        reason: 'wrong_item_received',
        notes: 'Received Amber version by mistake.',
      },
    ],
    method: {
      id: 'prepaid_label',
      name: 'Prepaid Shipping Label',
      carrier: 'USPS via Shippo',
      description: 'Prepaid return label',
      fee: 0,
      feeLabel: 'FREE (Free Return product)',
      estimatedDays: 'Completed',
      noPrinterNeeded: false,
      instructions: ['Return received and verified.'],
    },
    resolution: 'original_payment',
    financials: {
      itemsTotal: 95.0,
      returnFee: 0,
      bonusCredit: 0,
      finalRefundAmount: 95.0,
    },
    tracking: {
      carrier: 'UPS',
      trackingNumber: '1Z9999999999999999',
      trackingUrl: 'https://www.ups.com/track',
      qrCodeValue: 'RET-720194',
    },
    timeline: [
      {
        status: 'return_requested',
        title: 'Return Requested',
        description: 'Customer selected incorrect item received.',
        timestamp: 'Aug 17, 2026 · 09:00 AM',
        completed: true,
        current: false,
      },
      {
        status: 'received',
        title: 'Item Received & Inspected',
        description: 'Inspected at fulfillment center. Item condition verified.',
        timestamp: 'Aug 19, 2026 · 11:30 AM',
        completed: true,
        current: false,
      },
      {
        status: 'refund_completed',
        title: 'Refund Issued to Original Payment',
        description: '$95.00 refunded to Visa ending in 4242.',
        timestamp: 'Aug 19, 2026 · 01:15 PM',
        completed: true,
        current: true,
      },
    ],
  },
};
